# Self-hosted
autodiscover: true
autodiscoverFilter: "!/.*Mirror/.+/"
logFileLevel: error

# Repository
automerge: true
commitBodyTable: true
configMigration: true
dependencyDashboard: true
gitLabIgnoreApprovals: true

hostRules:
  - enableHttp2: true
lockFileMaintenance:
  enabled: true
platformAutomerge: true
