name: Renovate

on:
  schedule:
    - cron: 07 */3 * * *

  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    container: renovate/renovate:latest
    steps:
      - name: Load config
        run: curl https://raw.githubusercontent.com/Apocalypsor/Gitea-Sync/main/.github/renovate/config.yaml > /tmp/config.yaml
      - name: Self-hosted Renovate
        run: renovate || echo "failed"
        env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_USERNAME: ${{ secrets.RENOVATE_USERNAME }}
          RENOVATE_ENDPOINT: ${{ secrets.RENOVATE_ENDPOINT }}
          RENOVATE_PLATFORM: gitea
          RENOVATE_GIT_URL: endpoint
          RENOVATE_CONFIG_FILE: /tmp/config.yaml
          RENOVATE_GIT_PRIVATE_KEY: ${{ secrets.RENOVATE_GIT_PRIVATE_KEY }}
          LOG_LEVEL: debug
          GITHUB_COM_TOKEN: ${{ secrets.GH_TOKEN }}
