name: Schedule

on:
  workflow_dispatch:

  schedule:
    - cron: 23 */6 * * *

jobs:
  schedule:
    name: Mirror
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install pipenv
          pipenv requirements > requirements.txt
          pip install -r requirements.txt
      - name: Mirror
        env:
          GH_USERNAME: ${{ github.actor }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TEA_URL: ${{ secrets.TEA_URL }}
          TEA_TOKEN: ${{ secrets.TEA_TOKEN }}
          TEA_ORG: ${{ secrets.TEA_ORG }}
        run: |
          python sync.py
